# Docker file for nextjs frontend
FROM node:18-alpine AS builder
# Set working directory
WORKDIR /app
# Copy package.json and package-lock.json
COPY package.json package-lock.json ./
# Install dependencies
RUN npm install --legacy-peer-deps
# Copy the rest of the application code 
COPY . .
# Build the application
RUN npm run build

# Production stage
FROM node:18-alpine AS production
# Set working directory
WORKDIR /app
# Copy only the necessary files from the builder stage
COPY --from=builder /app/package.json ./
COPY --from=builder /app/package-lock.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
# Set environment variable for production
ENV NODE_ENV=production
# Install only production dependencies
RUN npm install --only=production --legacy-peer-deps
# Set environment variable for the application port

ENV PORT=3000

# Start the application
CMD ["bun", "start"]